import Link from 'next/link'
import { ArrowLeft, CheckCircle } from 'lucide-react'
import Card from '@/components/Card'
import Button from '@/components/Button'

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <Link href="/" className="inline-flex items-center text-blue-600 hover:text-blue-800 mb-4">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Link>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
          <p className="text-gray-600">Last updated: January 2025</p>
        </div>

        <Card className="p-8">
          <div className="prose prose-gray max-w-none">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using ClipGenius ("the Service"), you accept and agree to be bound by the terms
              and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              ClipGenius is an AI-powered marketing automation platform that helps businesses with:
            </p>
            <ul>
              <li>Lead generation and qualification</li>
              <li>Content creation and social media management</li>
              <li>Automated outreach campaigns</li>
              <li>Analytics and reporting</li>
            </ul>

            <h2>3. User Accounts</h2>
            <h3>3.1 Account Creation</h3>
            <p>
              To use our service, you must create an account. You are responsible for maintaining the confidentiality
              of your account credentials and for all activities that occur under your account.
            </p>

            <h3>3.2 Account Types</h3>
            <ul>
              <li><strong>Free Tier:</strong> Limited access to basic features</li>
              <li><strong>Pro Tier:</strong> Full access to all features with higher limits</li>
              <li><strong>Agency Tier:</strong> White-label solution with team management</li>
            </ul>

            <h2>4. Acceptable Use Policy</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Send unsolicited commercial communications (spam)</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Transmit malicious code or viruses</li>
              <li>Attempt to gain unauthorized access to our systems</li>
            </ul>

            <h2>5. Content and Data</h2>
            <h3>5.1 User Content</h3>
            <p>
              You retain ownership of all content you create or upload to the Service. You grant us a license
              to use your content solely for providing the Service.
            </p>

            <h3>5.2 AI-Generated Content</h3>
            <p>
              Content generated by our AI tools is provided "as-is" without warranties. You are responsible
              for reviewing and modifying generated content before use.
            </p>

            <h2>6. Payment Terms</h2>
            <h3>6.1 Billing</h3>
            <p>
              Subscription fees are billed in advance on a monthly or annual basis. Payment is due upon
              receipt of invoice. Late payments may result in service suspension.
            </p>

            <h3>6.2 Refunds</h3>
            <p>
              We offer a 14-day money-back guarantee for new subscriptions. Refunds are processed within
              5-7 business days.
            </p>

            <h2>7. Data Privacy and Security</h2>
            <h3>7.1 Data Protection</h3>
            <p>
              We implement industry-standard security measures to protect your data. This includes encryption,
              access controls, and regular security audits.
            </p>

            <h3>7.2 GDPR Compliance</h3>
            <p>
              We are committed to GDPR compliance. You have the right to access, modify, or delete your personal data.
              Contact us for data-related requests.
            </p>

            <h2>8. Service Availability</h2>
            <p>
              We strive for 99.9% uptime but do not guarantee uninterrupted service. We reserve the right to
              perform maintenance and updates that may temporarily affect service availability.
            </p>

            <h2>9. Limitation of Liability</h2>
            <p>
              Our liability is limited to the amount paid for the service in the 12 months preceding the claim.
              We are not liable for indirect, incidental, or consequential damages.
            </p>

            <h2>10. Termination</h2>
            <p>
              Either party may terminate this agreement with 30 days written notice. Upon termination,
              your access to the service will cease, but we will retain your data for a reasonable period
              as required by law.
            </p>

            <h2>11. Contact Information</h2>
            <p>
              For questions about these Terms of Service, please contact us at:
            </p>
            <ul>
              <li>Email: legal@clipgenius.ai</li>
              <li>Phone: +1 (555) 123-4567</li>
              <li>Address: 123 Business Street, Tech City, TC 12345</li>
            </ul>
          </div>
        </Card>
      </div>
    </div>
  )
}